// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {context} from '../models';

export function Create(arg1:string,arg2:service.PostRequestOnlyData):Promise<service.ApiResponseSingle>;

export function Delete(arg1:string,arg2:service.GetOneRequestParams):Promise<service.ApiResponseSingle>;

export function DeleteMany(arg1:string,arg2:service.GetManyRequestParams):Promise<service.ApiResponseSingle>;

export function GetList(arg1:string,arg2:service.GetListRequestParams):Promise<service.ApiResponse>;

export function GetMany(arg1:string,arg2:service.GetManyRequestParams):Promise<service.ApiResponse>;

export function GetManyReference(arg1:string,arg2:service.GetManyRequestParams):Promise<service.ApiResponse>;

export function GetOne(arg1:string,arg2:service.GetOneRequestParams):Promise<service.ApiResponseSingle>;

export function Setup(arg1:context.Context):Promise<void>;

export function Update(arg1:string,arg2:service.PostRequestParamsSingle):Promise<service.ApiResponseSingle>;

export function UpdateMany(arg1:string,arg2:service.PostRequestParamsMulti):Promise<service.ApiResponseSingle>;
