// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1, arg2) {
  return window['go']['service']['ProviderService']['Create'](arg1, arg2);
}

export function Delete(arg1, arg2) {
  return window['go']['service']['ProviderService']['Delete'](arg1, arg2);
}

export function DeleteMany(arg1, arg2) {
  return window['go']['service']['ProviderService']['DeleteMany'](arg1, arg2);
}

export function GetList(arg1, arg2) {
  return window['go']['service']['ProviderService']['GetList'](arg1, arg2);
}

export function GetMany(arg1, arg2) {
  return window['go']['service']['ProviderService']['GetMany'](arg1, arg2);
}

export function GetManyReference(arg1, arg2) {
  return window['go']['service']['ProviderService']['GetManyReference'](arg1, arg2);
}

export function GetOne(arg1, arg2) {
  return window['go']['service']['ProviderService']['GetOne'](arg1, arg2);
}

export function Setup(arg1) {
  return window['go']['service']['ProviderService']['Setup'](arg1);
}

export function Update(arg1, arg2) {
  return window['go']['service']['ProviderService']['Update'](arg1, arg2);
}

export function UpdateMany(arg1, arg2) {
  return window['go']['service']['ProviderService']['UpdateMany'](arg1, arg2);
}
