// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackendURL() {
  return window['go']['main']['App']['BackendURL']();
}

export function EmptyProfile() {
  return window['go']['main']['App']['EmptyProfile']();
}

export function IsSetup() {
  return window['go']['main']['App']['IsSetup']();
}

export function SubmitProfile(arg1) {
  return window['go']['main']['App']['SubmitProfile'](arg1);
}
