// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BackendURL():Promise<string>;

export function EmptyProfile():Promise<main.Profile>;

export function IsSetup():Promise<boolean>;

export function SubmitProfile(arg1:main.Profile):Promise<void>;
